server:
  port: 8888
spring:
  application:
    name: Hadoop
  mvc:
    view:
      prefix: /
      suffix: .html
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  profiles:
    active: dev
